### ISSUE TITLE
Calling any of the libraries' extension methods will throw: System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by Mahdi7s** [NorthernLight1/N.EntityFrameworkCore.Extensions#47]
![image](https://github.com/NorthernLight1/N.EntityFrameworkCore.Extensions/assets/1885293/0a219957-4018-458c-b64b-b23e0379b3a6)

I tried to use this library in my asp.net core/ef core 8 project, but calling any of these methods BulkInsert/Update/Merge/Async will throw below exception:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=N.EntityFrameworkCore.Extensions
  StackTrace:
   at N.EntityFrameworkCore.Extensions.DbTransactionContext..ctor(DbContext context, Nullable`1 commandTimeout, ConnectionBehavior connectionBehavior, Boolean openConnection)
   at N.EntityFrameworkCore.Extensions.BulkOperation`1..ctor(DbContext dbContext, BulkOptions options, Expression`1 inputColumns, Expression`1 ignoreColumns)
   at N.EntityFrameworkCore.Extensions.DbContextExtensionsAsync.<BulkInsertAsync>d__7`1.MoveNext()
   at N.EntityFrameworkCore.Extensions.DbContextExtensionsAsync.<BulkInsertAsync>d__6`1.MoveNext()
   at Server.Data.EfRepository`1.<InsertRange>d__10.MoveNext() in C:\Users\Mahdi\source\repos\Mahdi7s\Server\Data\EfRepository.cs:line 69

  This exception was originally thrown at this call stack:
    [External Code]
    Server.Data.EfRepository<TEntity>.InsertRange(System.Collections.Generic.IEnumerable<TEntity>, bool) in EfRepository.cs

**Comment by NorthernLight1** [comment]
What version of EntityFrameworkCore are you using?

**Comment by Mahdi7s** [comment]
> What version of EntityFrameworkCore are you using? Are you using the latest version of N.EntityFrameworkCore.Extensions?

![image](https://github.com/NorthernLight1/N.EntityFrameworkCore.Extensions/assets/1885293/ab9aa89f-4898-4ca9-a3e3-237014bbe97b)
8.0.2

**Comment by NorthernLight1** [comment]
Are you using the latest version of N.EntityFrameworkCore.Extensions? 

You may need to download the source code from Github and then debug against it to get the full call stack information. You will also be able to see exactly where the exception is being thrown. 

There is a unit test project that covers all the operations, and all of the test cases pass without any exceptions. I even added one for passing in entities using IEnumerable<T> but it also passed.  Once we figure out what is causing this issue, I will add a new test case for it.

**Comment by hongjs** [comment]
faced the same thing in v8.0.0.4

**Comment by NorthernLight1** [comment]
hongjs, 

1. What version of .NET are you targeting for your application?
2. What version of EF core are you using?
3. What version of N.EntityFrameworkCore.Extensions are you using?
4.

**Comment by NorthernLight1** [comment]
@Mahdi7s , @hongjs 

This issue will be closed if no response is given within 10 days.

**Comment by hongjs** [comment]
> @hongjs,
> 
> 1. What version of .NET are you targeting for your application?
> 2. What version of EF core are you using?
> 3. What version of N.EntityFrameworkCore.Extensions are you using?
> 
> I went ahead and tested the latest version of N.EntityFrameworkCore.Extensions (v8.0.0.4) and I was not able to replicate this issue.

Thanks for response, here is my info

Name|Version
--|--
MySQL|8.3.0
Microsoft.EntityFrameworkCore|8.0.1
Dotnet|8.0.101
OS|Mac M2 Pro - OS X 14.3 - arm64
N.EntityFrameworkCore|8.0.0.4


```csharp
// Code
using N.EntityFrameworkCore.Extensions;
...
_dbContext.BulkInsertAsync(insertItems)
...

// Error
Object reference not set to an instance of an object.
   at N.EntityFrameworkCore.Extensions.DbTransactionContext..ctor(DbContext context, Nullable`1 commandTimeout, ConnectionBehavior connectionBehavior, Boolean openConnection)
   at N.EntityFrameworkCore.Extensions.BulkOperation`1..ctor(DbContext dbContext, BulkOptions options, Expression`1 inputColumns, Expression`1 ignoreColumns)
   at N.EntityFrameworkCore.Extensions.DbContextExtensionsAsync.BulkInsertAsync[T](DbContext context, IEnumerable`1 entities, BulkInsertOptions`1 options, CancellationToken cancellationToken)
   at N.EntityFrameworkCore.Extensions.DbContextExtensionsAsync.BulkInsertAsync[T](DbContext context, IEnumerable`1 entities, CancellationToken cancellationToken)
   at MyProject.Infrastructure.Repositories.MyRepository.MyBulkSave(IList`1 insertItems, IList`1 updateItems) in /Users/path/to/project/src/MyProject.Infrastructure/Repositories/MyRepository.cs:line 150
```

**Comment by sky3913** [comment]
I've got the same error

What version of .NET are you targeting for your application? NET 8
What version of EF core are you using? EF Core 8
What version of N.EntityFrameworkCore.Extensions are you using? 8.0.0.4

error on this line
`await _dbContext.BulkInsertAsync(list);`

**Comment by siglar** [comment]
https://github.com/NorthernLight1/N.EntityFrameworkCore.Extensions/issues/29#issuecomment-1703997443

I see you've stated that only works with SQL Server here @NorthernLight1. You need to make this clear in the repository readme, or I think you'll be getting more issues like this moving forward 😆

**Comment by NorthernLight1** [comment]
signlar,

Thanks for pointing that out. I will update the README.md file so that it is clear it only support SQL Server.

**Comment by hongjs** [comment]
> signlar,
> 
> Thanks for pointing that out. I will update the README.md file so that it is clear it only support SQL Server.

Thanks for your confirmation
