### ISSUE TITLE
DatabaseGeneratedOption.None required for Primary Guid Id

### ISSUE THREAD

**Issue by SpaceOgre** [NorthernLight1/N.EntityFrameworkCore.Extensions#65]
**Describe the bug**
We are using Guids for our Ids, and if my understanding is correct the default convention for EF Core is to auto generat it on the client when calling SaveChanges. For the entities that I now do want to Bulk Insert I'm manually setting the Id in code.

But when I call BulkInsert it skips the Id column and I get an SQL exception:
```
 Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Id', table 'master.dbo.StudentReportImports'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__210_1(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRawAsync(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
   at N.EntityFrameworkCore.Extensions.DabaseFacadeExtensionsAsync.ExecuteSqlAsync(DatabaseFacade database, String sql, Object[] parameters, Nullable`1 commandTimeout, CancellationToken cancellationToken)
   at N.EntityFrameworkCore.Extensions.DabaseFacadeExtensionsAsync.ExecuteSqlAsync(DatabaseFacade database, String sql, Nullable`1 commandTimeout, CancellationToken cancellationToken)
   at N.EntityFrameworkCore.Extensions.BulkOperation`1.ExecuteMergeAsync(Dictionary`2 entityMap, Expression`1 mergeOnCondition, Boolean autoMapOutput, Boolean insertIfNotExists, Boolean update, Boolean delete, CancellationToken cancellationToken)
   at N.EntityFrameworkCore.Extensions.DbContextExtensionsAsync.BulkInsertAsync[T](DbContext context, IEnumerable`1 entities, BulkInsertOptions`1 options, CancellationToken cancellationToken)
   at N.EntityFrameworkCore.Extensions.DbContextExtensionsAsync.BulkInsertAsync[T](DbContext context, IEnumerable`1 entities, Action`1 optionsAction, CancellationToken cancellationToken)
```

If I add this attribute `[DatabaseGenerated(DatabaseGeneratedOption.None)]` to the Id property then it works as it should.

**Expected behavior**
I would expect it to work without the attribute since it is the default convention in EF Core to not create database generated values for Guid Ids.

**Comment by SpaceOgre** [comment]
`KeepIdentity = true` does not help.
The CloneTable part gets the Id column without the attribute but not the Merge statment.

**Comment by SpaceOgre** [comment]
Looked some more into it and it seems like the problem only exist on the async version.

```csharp
if(keepIdentity)
{
    columnsToInsert = columnsToInsert.Union(TableMapping.GetPrimaryKeyColumns());
}
```

This part is missing from the async version of ExecuteMergeAsync

**Comment by NorthernLight1** [comment]
SpaceOrge,

I made some recent fixes to the development branch and I believe it fixed this issue already. You are welcome to submit a pull request, but you may need to adjust your code now and do another commit.
